### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by knkrth** [h44z/Sprinternet-Device-Manager#4]
As we can see the original [odm](https://github.com/Fmstrat/odm) project is dead long time ago. You have managed to rebase the code & add some updates. 

Now your project seems to be dead, As you have declare "DISCONTINUED" 

Is there any open source alternation for the  android device management with full features?

**Comment by h44z** [comment]
I do not currently use a device manager for Android anymore, so I don't know any open source alternatives :(
